const productsData=[
  {
    id:"p1",
    image:"https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
    price:{zh:"¥899 / 件",en:"US$129 / unit",ja:"¥18,800 / 台",ms:"RM599 / unit"},
    name:{zh:"智能旗舰手机",en:"Smart Flagship Phone",ja:"スマートフラッグシップフォン",ms:"Telefon Pintar Flagship"},
    desc:{zh:"6.7 英寸高清屏幕，长续航与多场景影像能力，适合零售与渠道分销。",en:"6.7-inch display, long battery life and versatile imaging for retail and channel distribution.",ja:"6.7インチ高精細ディスプレイ、長時間駆動、多彩な撮影性能を備えた人気モデルです。",ms:"Skrin 6.7 inci, bateri tahan lama dan keupayaan kamera serba guna untuk pasaran runcit."}
  },
  {
    id:"p2",
    image:"https://images.unsplash.com/photo-1585386959984-a41552231658?auto=format&fit=crop&w=900&q=80",
    price:{zh:"¥399 / 件",en:"US$58 / unit",ja:"¥8,200 / 台",ms:"RM269 / unit"},
    name:{zh:"真无线降噪耳机",en:"Wireless Noise-Cancelling Earbuds",ja:"完全ワイヤレスノイズキャンセリングイヤホン",ms:"Fon Telinga Tanpa Wayar ANC"},
    desc:{zh:"轻量化佩戴设计，音质清晰，适合消费电子与礼品渠道市场。",en:"Lightweight design with clear sound, ideal for consumer electronics and gift channels.",ja:"軽量設計と高音質を両立し、家電販路やギフト需要に適しています。",ms:"Reka bentuk ringan dan audio jelas, sesuai untuk elektronik pengguna dan saluran hadiah."}
  },
  {
    id:"p3",
    image:"https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=900&q=80",
    price:{zh:"¥699 / 件",en:"US$99 / unit",ja:"¥14,600 / 台",ms:"RM459 / unit"},
    name:{zh:"智能扫地机器人",en:"Smart Robot Vacuum",ja:"スマートロボット掃除機",ms:"Robot Vakum Pintar"},
    desc:{zh:"适合家庭与小型办公场景，支持智能规划清扫与自动回充。",en:"Designed for home and small office use with smart route planning and auto charging.",ja:"家庭や小規模オフィス向けに、スマート清掃ルートと自動充電機能を搭載。",ms:"Untuk rumah dan pejabat kecil dengan laluan pembersihan pintar dan pengecasan automatik."}
  },
  {
    id:"p4",
    image:"https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=900&q=80",
    price:{zh:"¥499 / 件",en:"US$72 / unit",ja:"¥10,400 / 台",ms:"RM329 / unit"},
    name:{zh:"智能运动手表",en:"Smart Sports Watch",ja:"スマートスポーツウォッチ",ms:"Jam Sukan Pintar"},
    desc:{zh:"支持健康监测、运动记录与消息提醒，适合线上线下多渠道销售。",en:"Health tracking, sports recording and notifications for both online and offline channels.",ja:"健康管理、運動記録、通知機能を備え、幅広い販路で展開しやすい製品です。",ms:"Pemantauan kesihatan, rekod sukan dan notifikasi, sesuai untuk jualan pelbagai saluran."}
  }
];

const i18n={
  zh:{
    companyName:"深圳开智镁客",
    brandTag:"Cross-Border Trade",
    navHome:"首页",
    navCompany:"公司介绍",
    navProducts:"产品中心",
    navContact:"联系我们",
    homeHeroEyebrow1:"全球供应链 · 高效履约",
    homeHeroTitle1:"链接全球市场的跨境贸易伙伴",
    homeHeroDesc1:"聚焦消费电子、智能家居与精品生活方式产品，为全球渠道客户提供稳定货源、品质交付与品牌增长支持。",
    homeHeroBtnPrimary:"查看产品",
    homeHeroBtnSecondary:"获取报价",
    homeHeroEyebrow2:"品牌出海 · 专业服务",
    homeHeroTitle2:"面向 B 端客户的一站式跨境电商解决方案",
    homeHeroDesc2:"从选品、采购、质检到国际物流、售后协同，帮助企业快速进入海外市场，建立长期竞争力。",
    homeHeroBtnPrimary2:"了解我们",
    homeHeroBtnSecondary2:"联系顾问",
    homeHeroEyebrow3:"智能选品 · 多语沟通",
    homeHeroTitle3:"响应全球客户需求，打造值得信赖的合作体验",
    homeHeroDesc3:"支持多语言展示与国际化商务沟通，让您的客户从第一眼开始就感受到专业、稳定与高效。",
    homeHeroBtnPrimary3:"热销产品",
    homeHeroBtnSecondary3:"立即咨询",
    homeProductsKicker:"核心产品",
    homeProductsTitle:"面向全球市场的精选产品矩阵",
    homeProductsDesc:"聚焦高需求、高复购、高性价比品类，满足不同渠道与地区市场需求。",
    homeAdvantagesKicker:"企业优势",
    homeAdvantagesTitle:"为什么全球客户选择我们",
    homeAdvantagesDesc:"以供应链能力、品质把控和国际化服务体系，为客户持续创造长期价值。",
    advTitle1:"稳定供应链",
    advDesc1:"整合优质工厂与成熟采购网络，保障交付周期、品质一致性与产能稳定。",
    advTitle2:"严格质检",
    advDesc2:"从原材料到成品出货建立多重检测流程，降低退货率与售后风险。",
    advTitle3:"全球物流",
    advDesc3:"支持海运、空运、快递与海外仓协同，适配多地区履约需求。",
    advTitle4:"多语服务",
    advDesc4:"提供多语沟通、定制资料与快速响应，让国际合作更高效顺畅。",
    homeCtaKicker:"开启合作",
    homeCtaTitle:"让您的品牌与产品更快触达海外客户",
    homeCtaDesc:"欢迎联系我们获取产品目录、渠道报价与跨境合作建议，我们将在 24 小时内回复。",
    homeCtaBtn1:"立即联系",
    homeCtaBtn2:"了解公司",
    companyHeroKicker:"关于我们",
    companyHeroTitle:"以全球视野服务跨境贸易与品牌出海",
    companyHeroDesc:"我们专注于跨境电商与国际贸易服务，致力于为全球客户提供高品质产品、稳定供应链与高效率合作体验。",
    companyIntroKicker:"企业简介",
    companyIntroTitle:"连接制造实力与海外市场",
    companyIntroText:"深圳开智镁客总部位于亚洲核心供应链区域，深耕跨境出口业务多年，服务对象覆盖品牌商、批发商、零售商、电商平台卖家及区域代理商。我们通过稳定的产品体系、透明的商务流程和国际化服务标准，帮助客户提升采购效率并拓展海外市场。",
    companyStat1:"服务国家与地区",
    companyStat2:"合作渠道客户",
    companyStat3:"优质供应链伙伴",
    companyStat4:"快速商务响应",
    companyCultureKicker:"企业文化",
    companyCultureTitle:"长期主义、品质导向、合作共赢",
    companyCultureTitle1:"诚信透明",
    companyCultureDesc1:"坚持真实沟通、透明报价与可追溯流程，建立可靠合作关系。",
    companyCultureTitle2:"客户成功",
    companyCultureDesc2:"以客户增长为目标，持续优化产品结构、服务流程与交付效率。",
    companyCultureTitle3:"全球协作",
    companyCultureDesc3:"尊重多元市场文化与商业习惯，用国际化视角推进长期合作。",
    companyAdvantagesKicker:"核心优势",
    companyAdvantagesTitle:"我们如何为客户创造价值",
    companyAdvTitle1:"高效选品与定制能力",
    companyAdvDesc1:"结合海外市场趋势与渠道特征，提供高匹配度产品方案与定制支持。",
    companyAdvTitle2:"稳定交付与品控体系",
    companyAdvDesc2:"依托成熟供应链与标准化质检流程，提升产品稳定性与交货可靠性。",
    companyAdvTitle3:"灵活国际物流方案",
    companyAdvDesc3:"支持多种运输与仓配模式，帮助客户平衡时效、成本与库存周转。",
    companyAdvTitle4:"专业多语言商务服务",
    companyAdvDesc4:"提供中文、英文、日语、马来语支持，提升国际沟通效率与合作体验。",
    companyServiceKicker:"服务介绍",
    companyServiceTitle:"覆盖跨境业务全链路的专业服务",
    companyServiceTitle1:"产品咨询",
    companyServiceDesc1:"提供市场匹配度分析、选品建议与产品目录支持。",
    companyServiceTitle2:"采购跟进",
    companyServiceDesc2:"从打样到量产、从排单到验货，全流程透明协同。",
    companyServiceTitle3:"物流履约",
    companyServiceDesc3:"根据目标市场提供海运、空运、快递或海外仓方案。",
    companyServiceTitle4:"售后协同",
    companyServiceDesc4:"协助处理售后反馈、资料更新与长期复购支持。",
    productsHeroKicker:"产品中心",
    productsHeroTitle:"多品类精选产品，服务全球渠道客户",
    productsHeroDesc:"所有产品信息、名称、价格与简介均支持四种语言同步切换，方便国际业务展示与沟通。",
    productsListKicker:"产品列表",
    productsListTitle:"热销产品推荐",
    productsListDesc:"适合跨境批发、电商零售、品牌定制与区域代理等多种合作模式。",
    contactHeroKicker:"联系我们",
    contactHeroTitle:"欢迎与我们建立跨境业务合作",
    contactHeroDesc:"可通过电话、邮箱、WhatsApp 及社交媒体与我们沟通，也可以直接提交表单，我们会尽快回复您。",
    contactAddressTitle:"地址",
    contactAddressText:"中国深圳市南山区科技园国际贸易中心 18 楼",
    contactPhoneTitle:"电话",
    contactEmailTitle:"邮箱",
    contactFormKicker:"在线留言",
    contactFormTitle:"发送您的需求",
    contactFormDesc:"纯前端演示表单，提交后将在当前页面显示成功提示。",
    formName:"姓名",
    formEmail:"邮箱",
    formPhone:"电话/WhatsApp",
    formMessage:"留言内容",
    formSubmit:"提交留言",
    formSuccess:"留言提交成功，我们会尽快与您联系。",
    footerText:"专业跨境电商与国际贸易合作伙伴",
    footerCopy:"© 2025 深圳开智镁客. All Rights Reserved."
  },
  en:{
    companyName:"ShenZhenKZMK",
    brandTag:"Cross-Border Trade",
    navHome:"Home",
    navCompany:"Company",
    navProducts:"Products",
    navContact:"Contact",
    homeHeroEyebrow1:"Global Supply Chain · Reliable Fulfillment",
    homeHeroTitle1:"Your Trusted Partner in Global Cross-Border Trade",
    homeHeroDesc1:"Focused on consumer electronics, smart home, and lifestyle products, we deliver stable supply, quality fulfillment, and growth support for global channel partners.",
    homeHeroBtnPrimary:"View Products",
    homeHeroBtnSecondary:"Get Quote",
    homeHeroEyebrow2:"Brand Expansion · Professional Service",
    homeHeroTitle2:"One-Stop Cross-Border E-Commerce Solutions for B2B Clients",
    homeHeroDesc2:"From sourcing and procurement to QC, international logistics, and after-sales coordination, we help businesses enter overseas markets with speed and confidence.",
    homeHeroBtnPrimary2:"About Us",
    homeHeroBtnSecondary2:"Contact Advisor",
    homeHeroEyebrow3:"Smart Selection · Multilingual Communication",
    homeHeroTitle3:"Responding to Global Demand with a Trusted Partnership Experience",
    homeHeroDesc3:"With multilingual content and international business communication, your clients experience professionalism, stability, and efficiency from the first impression.",
    homeHeroBtnPrimary3:"Best Sellers",
    homeHeroBtnSecondary3:"Contact Now",
    homeProductsKicker:"Core Products",
    homeProductsTitle:"Selected Product Portfolio for Global Markets",
    homeProductsDesc:"Targeting high-demand, high-repurchase, and high-value categories across different regions and channels.",
    homeAdvantagesKicker:"Why Us",
    homeAdvantagesTitle:"Why Global Clients Choose Us",
    homeAdvantagesDesc:"We create long-term value through supply chain strength, quality control, and international service capability.",
    advTitle1:"Stable Supply Chain",
    advDesc1:"Integrated factories and mature sourcing networks ensure stable capacity, delivery cycles, and consistent quality.",
    advTitle2:"Strict Quality Control",
    advDesc2:"Multi-step inspections from raw materials to finished goods reduce return rates and after-sales risk.",
    advTitle3:"Global Logistics",
    advDesc3:"Support for sea freight, air freight, express delivery, and overseas warehouse coordination.",
    advTitle4:"Multilingual Service",
    advDesc4:"Multilingual communication, tailored materials, and fast response make global cooperation smoother.",
    homeCtaKicker:"Start Cooperation",
    homeCtaTitle:"Bring Your Brand and Products to Overseas Customers Faster",
    homeCtaDesc:"Contact us for catalogs, pricing, and cross-border cooperation suggestions. We will reply within 24 hours.",
    homeCtaBtn1:"Contact Us",
    homeCtaBtn2:"About Company",
    companyHeroKicker:"About Us",
    companyHeroTitle:"Serving Cross-Border Trade and Brand Expansion with a Global Vision",
    companyHeroDesc:"We specialize in cross-border e-commerce and international trade, delivering quality products, a stable supply chain, and efficient cooperation for global clients.",
    companyIntroKicker:"Company Profile",
    companyIntroTitle:"Connecting Manufacturing Strength with Overseas Markets",
    companyIntroText:"Shenzhen Kaizhi Meike is based in Asia’s core supply chain region and has many years of export experience. We serve brand owners, wholesalers, retailers, e-commerce sellers, and regional distributors with stable products, transparent business processes, and international service standards.",
    companyStat1:"Countries & Regions Served",
    companyStat2:"Channel Clients",
    companyStat3:"Supply Chain Partners",
    companyStat4:"Fast Business Response",
    companyCultureKicker:"Culture",
    companyCultureTitle:"Long-Term Thinking, Quality First, Mutual Success",
    companyCultureTitle1:"Integrity & Transparency",
    companyCultureDesc1:"We build trust through honest communication, transparent pricing, and traceable processes.",
    companyCultureTitle2:"Customer Success",
    companyCultureDesc2:"We optimize products, workflow, and delivery speed around our clients’ business growth.",
    companyCultureTitle3:"Global Collaboration",
    companyCultureDesc3:"We respect diverse markets and business practices with an international mindset.",
    companyAdvantagesKicker:"Core Strengths",
    companyAdvantagesTitle:"How We Create Value for Clients",
    companyAdvTitle1:"Efficient Product Selection & Customization",
    companyAdvDesc1:"We match products with overseas trends and channel needs, including customization support.",
    companyAdvTitle2:"Stable Delivery & QC System",
    companyAdvDesc2:"Mature supply chains and standardized inspection processes improve product reliability.",
    companyAdvTitle3:"Flexible International Logistics",
    companyAdvDesc3:"Multiple transport and warehousing options balance lead time, cost, and inventory turnover.",
    companyAdvTitle4:"Professional Multilingual Service",
    companyAdvDesc4:"Chinese, English, Japanese, and Malay support improves communication efficiency.",
    companyServiceKicker:"Services",
    companyServiceTitle:"Professional Services Covering the Entire Cross-Border Workflow",
    companyServiceTitle1:"Product Consulting",
    companyServiceDesc1:"Market matching analysis, product selection advice, and catalog support.",
    companyServiceTitle2:"Procurement Follow-Up",
    companyServiceDesc2:"Transparent coordination from sampling and production to scheduling and inspection.",
    companyServiceTitle3:"Logistics Fulfillment",
    companyServiceDesc3:"Sea freight, air freight, express, or overseas warehouse solutions by target market.",
    companyServiceTitle4:"After-Sales Coordination",
    companyServiceDesc4:"Support for feedback handling, documentation updates, and repeat orders.",
    productsHeroKicker:"Products",
    productsHeroTitle:"Selected Multi-Category Products for Global Channel Partners",
    productsHeroDesc:"All product names, prices, descriptions, and buttons switch instantly across four languages.",
    productsListKicker:"Product List",
    productsListTitle:"Best-Selling Products",
    productsListDesc:"Suitable for wholesale, e-commerce retail, private label, and regional distribution.",
    contactHeroKicker:"Contact Us",
    contactHeroTitle:"Let’s Build Your Cross-Border Business Together",
    contactHeroDesc:"Reach us via phone, email, WhatsApp, and social media, or submit the form directly for a quick reply.",
    contactAddressTitle:"Address",
    contactAddressText:"18F, International Trade Center, Nanshan Tech Park, Shenzhen, China",
    contactPhoneTitle:"Phone",
    contactEmailTitle:"Email",
    contactFormKicker:"Message Form",
    contactFormTitle:"Send Your Inquiry",
    contactFormDesc:"This is a front-end demo form. A success notice will appear on this page after submission.",
    formName:"Name",
    formEmail:"Email",
    formPhone:"Phone / WhatsApp",
    formMessage:"Message",
    formSubmit:"Submit",
    formSuccess:"Your message has been submitted successfully. We will contact you soon.",
    footerText:"Professional partner for cross-border e-commerce and international trade",
    footerCopy:"© 2025 ShenZhenKZMK. All Rights Reserved."
  },
  ja:{
    companyName:"深圳開智鎂客",
    brandTag:"Cross-Border Trade",
    navHome:"ホーム",
    navCompany:"会社案内",
    navProducts:"製品一覧",
    navContact:"お問い合わせ",
    homeHeroEyebrow1:"グローバル供給網 · 安定した履行",
    homeHeroTitle1:"世界市場をつなぐ信頼の越境貿易パートナー",
    homeHeroDesc1:"家電、スマートホーム、ライフスタイル製品を中心に、世界中の販路パートナーへ安定供給と品質ある納品を提供します。",
    homeHeroBtnPrimary:"製品を見る",
    homeHeroBtnSecondary:"見積依頼",
    homeHeroEyebrow2:"海外展開 · 専門サービス",
    homeHeroTitle2:"B2B向けワンストップ越境ECソリューション",
    homeHeroDesc2:"選定、調達、品質管理、国際物流、アフターサポートまで、海外進出を総合的に支援します。",
    homeHeroBtnPrimary2:"会社を見る",
    homeHeroBtnSecondary2:"相談する",
    homeHeroEyebrow3:"スマート選定 · 多言語対応",
    homeHeroTitle3:"世界の需要に応える、信頼できる協業体験",
    homeHeroDesc3:"多言語表示と国際的な商談対応により、第一印象から専門性と安心感を届けます。",
    homeHeroBtnPrimary3:"人気製品",
    homeHeroBtnSecondary3:"今すぐ相談",
    homeProductsKicker:"主要製品",
    homeProductsTitle:"世界市場向けの厳選製品ラインアップ",
    homeProductsDesc:"高需要・高再購入率・高コストパフォーマンスのカテゴリを厳選しています。",
    homeAdvantagesKicker:"強み",
    homeAdvantagesTitle:"世界中の顧客に選ばれる理由",
    homeAdvantagesDesc:"供給力、品質管理、国際対応力で長期的な価値を創出します。",
    advTitle1:"安定した供給網",
    advDesc1:"優良工場と成熟した調達ネットワークにより、納期・品質・生産能力を安定化します。",
    advTitle2:"厳格な品質管理",
    advDesc2:"原材料から完成品まで多段階の検査で返品率とアフターリスクを低減します。",
    advTitle3:"グローバル物流",
    advDesc3:"海上、航空、宅配、海外倉庫連携など多様な物流ニーズに対応します。",
    advTitle4:"多言語サービス",
    advDesc4:"多言語対応、資料作成、迅速な返信で国際協業を円滑に進めます。",
    homeCtaKicker:"協業開始",
    homeCtaTitle:"ブランドと製品をより早く海外顧客へ",
    homeCtaDesc:"製品カタログ、価格表、越境協業のご提案についてお気軽にお問い合わせください。24時間以内に返信します。",
    homeCtaBtn1:"お問い合わせ",
    homeCtaBtn2:"会社案内",
    companyHeroKicker:"会社案内",
    companyHeroTitle:"グローバル視点で越境貿易と海外展開を支援",
    companyHeroDesc:"当社は越境ECと国際貿易に特化し、高品質な製品、安定供給、効率的な協業体験を提供します。",
    companyIntroKicker:"会社概要",
    companyIntroTitle:"製造力と海外市場をつなぐ",
    companyIntroText:"深圳開智鎂客はアジアの主要サプライチェーン地域に拠点を置き、長年にわたり輸出業務を展開しています。ブランド企業、卸売業者、小売業者、EC販売者、地域代理店に向けて、安定した製品供給と透明な取引プロセスを提供しています。",
    companyStat1:"対応国・地域",
    companyStat2:"取引チャネル顧客",
    companyStat3:"サプライチェーンパートナー",
    companyStat4:"迅速な商談対応",
    companyCultureKicker:"企業文化",
    companyCultureTitle:"長期志向・品質重視・共創共栄",
    companyCultureTitle1:"誠実さと透明性",
    companyCultureDesc1:"誠実な対話、透明な価格、追跡可能な工程で信頼関係を構築します。",
    companyCultureTitle2:"顧客成功",
    companyCultureDesc2:"お客様の成長を中心に、製品構成、業務フロー、納品効率を改善します。",
    companyCultureTitle3:"グローバル協業",
    companyCultureDesc3:"多様な市場文化と商習慣を尊重し、国際的な視点で協業を進めます。",
    companyAdvantagesKicker:"主要優位性",
    companyAdvantagesTitle:"お客様へ価値を届ける方法",
    companyAdvTitle1:"効率的な製品選定とカスタマイズ",
    companyAdvDesc1:"海外トレンドと販路特性に合わせた製品提案とカスタム対応を行います。",
    companyAdvTitle2:"安定納品と品質管理体制",
    companyAdvDesc2:"成熟した供給網と標準化された検査工程で信頼性を高めます。",
    companyAdvTitle3:"柔軟な国際物流",
    companyAdvDesc3:"納期、コスト、在庫回転のバランスに応じた物流設計が可能です。",
    companyAdvTitle4:"多言語商務対応",
    companyAdvDesc4:"中国語、英語、日本語、マレー語での対応が可能です。",
    companyServiceKicker:"サービス",
    companyServiceTitle:"越境ビジネス全体を支える専門サービス",
    companyServiceTitle1:"製品コンサルティング",
    companyServiceDesc1:"市場適合分析、製品提案、カタログ提供を行います。",
    companyServiceTitle2:"調達フォロー",
    companyServiceDesc2:"サンプルから量産、スケジュール、検品まで透明に連携します。",
    companyServiceTitle3:"物流履行",
    companyServiceDesc3:"対象市場に応じて海運、空運、宅配、海外倉庫を提案します。",
    companyServiceTitle4:"アフターサポート",
    companyServiceDesc4:"フィードバック対応、資料更新、継続発注支援を行います。",
    productsHeroKicker:"製品一覧",
    productsHeroTitle:"世界の販路顧客向け厳選プロダクト",
    productsHeroDesc:"製品名、価格、説明文など、すべて4言語で即時切替に対応しています。",
    productsListKicker:"製品リスト",
    productsListTitle:"人気製品",
    productsListDesc:"卸売、EC販売、ブランドOEM、地域代理など多様な協業形態に対応します。",
    contactHeroKicker:"お問い合わせ",
    contactHeroTitle:"越境ビジネスの協業を始めましょう",
    contactHeroDesc:"電話、メール、WhatsApp、SNS、またはフォーム送信でお気軽にご連絡ください。",
    contactAddressTitle:"住所",
    contactAddressText:"中国・深セン市南山区科技園 国際貿易センター 18階",
    contactPhoneTitle:"電話",
    contactEmailTitle:"メール",
    contactFormKicker:"お問い合わせフォーム",
    contactFormTitle:"ご要望を送信",
    contactFormDesc:"フロントエンドのみのデモフォームです。送信後、このページに完了メッセージが表示されます。",
    formName:"お名前",
    formEmail:"メール",
    formPhone:"電話 / WhatsApp",
    formMessage:"内容",
    formSubmit:"送信する",
    formSuccess:"送信が完了しました。担当者より追ってご連絡いたします。",
    footerText:"越境ECと国際貿易のプロフェッショナルパートナー",
    footerCopy:"© 2025 深圳開智鎂客. All Rights Reserved."
  },
  ms:{
    companyName:"Shenzhen Kaizhi Meike",
    brandTag:"Cross-Border Trade",
    navHome:"Laman Utama",
    navCompany:"Syarikat",
    navProducts:"Produk",
    navContact:"Hubungi Kami",
    homeHeroEyebrow1:"Rantaian Bekalan Global · Pemenuhan Cekap",
    homeHeroTitle1:"Rakan Dagang Rentas Sempadan Anda ke Pasaran Global",
    homeHeroDesc1:"Fokus pada elektronik pengguna, rumah pintar dan produk gaya hidup untuk menyediakan bekalan stabil, penghantaran berkualiti dan sokongan pertumbuhan jenama.",
    homeHeroBtnPrimary:"Lihat Produk",
    homeHeroBtnSecondary:"Dapatkan Sebut Harga",
    homeHeroEyebrow2:"Pengembangan Jenama · Servis Profesional",
    homeHeroTitle2:"Penyelesaian E-Dagang Rentas Sempadan Sehenti untuk Pelanggan B2B",
    homeHeroDesc2:"Daripada pemilihan produk, pembelian, QC hingga logistik antarabangsa dan koordinasi selepas jualan, kami membantu perniagaan memasuki pasaran luar negara dengan lebih pantas.",
    homeHeroBtnPrimary2:"Kenali Kami",
    homeHeroBtnSecondary2:"Hubungi Penasihat",
    homeHeroEyebrow3:"Pemilihan Pintar · Komunikasi Pelbagai Bahasa",
    homeHeroTitle3:"Memenuhi Keperluan Global dengan Pengalaman Kerjasama yang Dipercayai",
    homeHeroDesc3:"Dengan kandungan pelbagai bahasa dan komunikasi perniagaan antarabangsa, pelanggan anda akan merasai profesionalisme dan kecekapan sejak awal.",
    homeHeroBtnPrimary3:"Produk Terlaris",
    homeHeroBtnSecondary3:"Hubungi Sekarang",
    homeProductsKicker:"Produk Teras",
    homeProductsTitle:"Portfolio Produk Terpilih untuk Pasaran Global",
    homeProductsDesc:"Memfokuskan kategori permintaan tinggi, pembelian berulang tinggi dan nilai terbaik untuk pelbagai saluran pasaran.",
    homeAdvantagesKicker:"Kelebihan",
    homeAdvantagesTitle:"Mengapa Pelanggan Global Memilih Kami",
    homeAdvantagesDesc:"Kami mencipta nilai jangka panjang melalui keupayaan rantaian bekalan, kawalan kualiti dan servis antarabangsa.",
    advTitle1:"Rantaian Bekalan Stabil",
    advDesc1:"Gabungan kilang berkualiti dan rangkaian pembelian matang memastikan kapasiti dan penghantaran yang stabil.",
    advTitle2:"Kawalan Kualiti Ketat",
    advDesc2:"Pemeriksaan berlapis dari bahan mentah ke produk siap mengurangkan kadar pemulangan dan risiko selepas jualan.",
    advTitle3:"Logistik Global",
    advDesc3:"Sokongan untuk laut, udara, kurier dan gudang luar negara bagi pelbagai keperluan pemenuhan.",
    advTitle4:"Servis Pelbagai Bahasa",
    advDesc4:"Komunikasi pelbagai bahasa, bahan tersuai dan respon cepat memudahkan kerjasama global.",
    homeCtaKicker:"Mulakan Kerjasama",
    homeCtaTitle:"Bawa Jenama dan Produk Anda ke Pelanggan Luar Negara dengan Lebih Cepat",
    homeCtaDesc:"Hubungi kami untuk katalog produk, harga saluran dan cadangan kerjasama rentas sempadan. Kami akan membalas dalam 24 jam.",
    homeCtaBtn1:"Hubungi Kami",
    homeCtaBtn2:"Kenali Syarikat",
    companyHeroKicker:"Tentang Kami",
    companyHeroTitle:"Melayani Dagangan Rentas Sempadan dengan Visi Global",
    companyHeroDesc:"Kami pakar dalam e-dagang rentas sempadan dan perdagangan antarabangsa, menyediakan produk berkualiti, rantaian bekalan stabil dan pengalaman kerjasama yang cekap.",
    companyIntroKicker:"Profil Syarikat",
    companyIntroTitle:"Menghubungkan Kekuatan Pembuatan dengan Pasaran Luar Negara",
    companyIntroText:"Shenzhen Kaizhi Meike berpangkalan di rantau rantaian bekalan utama Asia dan berpengalaman luas dalam eksport. Kami melayani pemilik jenama, pemborong, peruncit, penjual e-dagang dan pengedar serantau melalui produk stabil, proses perniagaan telus dan standard servis antarabangsa.",
    companyStat1:"Negara & Wilayah Dilayani",
    companyStat2:"Pelanggan Saluran",
    companyStat3:"Rakan Rantaian Bekalan",
    companyStat4:"Respon Perniagaan Pantas",
    companyCultureKicker:"Budaya Korporat",
    companyCultureTitle:"Berfikiran Jangka Panjang, Utamakan Kualiti, Menang Bersama",
    companyCultureTitle1:"Integriti & Ketelusan",
    companyCultureDesc1:"Kami membina kepercayaan melalui komunikasi jujur, harga telus dan proses yang boleh dijejaki。",
    companyCultureTitle2:"Kejayaan Pelanggan",
    companyCultureDesc2:"Kami menambah baik produk, aliran kerja dan penghantaran berdasarkan pertumbuhan pelanggan。",
    companyCultureTitle3:"Kerjasama Global",
    companyCultureDesc3:"Kami menghormati kepelbagaian budaya pasaran dan amalan perniagaan dengan minda antarabangsa。",
    companyAdvantagesKicker:"Kekuatan Utama",
    companyAdvantagesTitle:"Bagaimana Kami Mencipta Nilai untuk Pelanggan",
    companyAdvTitle1:"Pemilihan Produk & Penyesuaian Efisien",
    companyAdvDesc1:"Kami memadankan produk dengan trend luar negara dan keperluan saluran, termasuk sokongan penyesuaian。",
    companyAdvTitle2:"Penghantaran Stabil & Sistem QC",
    companyAdvDesc2:"Rantaian bekalan matang dan proses pemeriksaan piawai meningkatkan kebolehpercayaan produk。",
    companyAdvTitle3:"Logistik Antarabangsa Fleksibel",
    companyAdvDesc3:"Pelbagai pilihan pengangkutan dan pergudangan mengimbangi masa, kos dan pusing ganti inventori。",
    companyAdvTitle4:"Servis Perniagaan Pelbagai Bahasa",
    companyAdvDesc4:"Sokongan dalam bahasa Cina, Inggeris, Jepun dan Melayu meningkatkan kecekapan komunikasi。",
    companyServiceKicker:"Perkhidmatan",
    companyServiceTitle:"Perkhidmatan Profesional Meliputi Keseluruhan Proses Rentas Sempadan",
    companyServiceTitle1:"Konsultasi Produk",
    companyServiceDesc1:"Analisis padanan pasaran, cadangan produk dan sokongan katalog。",
    companyServiceTitle2:"Susulan Pembelian",
    companyServiceDesc2:"Penyelarasan telus dari sampel dan pengeluaran hingga jadual dan pemeriksaan。",
    companyServiceTitle3:"Pemenuhan Logistik",
    companyServiceDesc3:"Penyelesaian laut, udara, kurier atau gudang luar negara mengikut pasaran sasaran。",
    companyServiceTitle4:"Koordinasi Selepas Jualan",
    companyServiceDesc4:"Sokongan untuk maklum balas, kemas kini dokumen dan pesanan berulang。",
    productsHeroKicker:"Pusat Produk",
    productsHeroTitle:"Produk Terpilih Pelbagai Kategori untuk Pelanggan Global",
    productsHeroDesc:"Semua nama produk, harga dan penerangan menyokong empat bahasa secara serentak。",
    productsListKicker:"Senarai Produk",
    productsListTitle:"Cadangan Produk Laris",
    productsListDesc:"Sesuai untuk borong rentas sempadan, runcit e-dagang, label peribadi dan pengedaran serantau。",
    contactHeroKicker:"Hubungi Kami",
    contactHeroTitle:"Mari Bina Kerjasama Perniagaan Rentas Sempadan Anda",
    contactHeroDesc:"Hubungi kami melalui telefon, e-mel, WhatsApp dan media sosial, atau hantar borang secara terus untuk respon pantas。",
    contactAddressTitle:"Alamat",
    contactAddressText:"Tingkat 18, Pusat Dagangan Antarabangsa, Taman Teknologi Nanshan, Shenzhen, China",
    contactPhoneTitle:"Telefon",
    contactEmailTitle:"E-mel",
    contactFormKicker:"Borang Hubungan",
    contactFormTitle:"Hantar Keperluan Anda",
    contactFormDesc:"Ini ialah borang demo front-end. Notis berjaya akan dipaparkan selepas penghantaran。",
    formName:"Nama",
    formEmail:"E-mel",
    formPhone:"Telefon / WhatsApp",
    formMessage:"Mesej",
    formSubmit:"Hantar",
    formSuccess:"Mesej anda telah berjaya dihantar. Kami akan menghubungi anda secepat mungkin。",
    footerText:"Rakan profesional untuk e-dagang rentas sempadan dan perdagangan antarabangsa",
    footerCopy:"© 2025 ShenZhenKZMK. All Rights Reserved."
  }
};

function getCurrentLang(){return localStorage.getItem("site-lang")||"zh";}
function setCurrentLang(lang){localStorage.setItem("site-lang",lang);}
function t(key,lang=getCurrentLang()){return i18n[lang]&&i18n[lang][key]?i18n[lang][key]:key;}

function productCardTemplate(product,lang){
  return `
    <article class="product-card reveal">
      <div class="product-image-wrap">
        <img class="product-image" src="${product.image}" alt="${product.name[lang]}" />
      </div>
      <div class="product-content">
        <h3 class="product-title">${product.name[lang]}</h3>
        <div class="product-price">${product.price[lang]}</div>
        <p class="product-desc">${product.desc[lang]}</p>
      </div>
    </article>
  `;
}

function renderProductGrids(lang=getCurrentLang()){
  const homeGrid=document.getElementById("homeProductsGrid");
  const productsGrid=document.getElementById("productsPageGrid");
  if(homeGrid) homeGrid.innerHTML=productsData.map((item)=>productCardTemplate(item,lang)).join("");
  if(productsGrid) productsGrid.innerHTML=productsData.map((item)=>productCardTemplate(item,lang)).join("");
  if(typeof observeReveal==="function") observeReveal();
}

function syncLanguageSelects(lang){
  document.querySelectorAll(".lang-select").forEach((select)=>{
    select.value=lang;
  });
}

function renderTexts(lang=getCurrentLang()){
  document.documentElement.lang=lang==="zh"?"zh-CN":lang;
  document.querySelectorAll("[data-i18n]").forEach((el)=>{
    const key=el.dataset.i18n;
    const value=t(key,lang);
    if(value) el.textContent=value;
  });
  syncLanguageSelects(lang);
  renderProductGrids(lang);
  const notice=document.getElementById("formNotice");
  if(notice&&!notice.classList.contains("hidden")) notice.textContent=t("formSuccess",lang);
}

document.addEventListener("DOMContentLoaded",()=>{
  const lang=getCurrentLang();
  renderTexts(lang);
  document.querySelectorAll(".lang-select").forEach((select)=>{
    select.addEventListener("change",()=>{
      const selected=select.value;
      setCurrentLang(selected);
      renderTexts(selected);
    });
  });
});
